Repository canonical/canonicalwebteam.store-api, pull requests merged in 2024-05, with the labels that each got.

#118 Add delete package endpoint
  canonicalwebteam/store_api/publisher.py
  canonicalwebteam/store_api/stores/snapstore.py
Labels: Review: QA +1, Review: Code +1

#119 Bump minor version
  pyproject.toml
Labels: Review: Code +1

#121 chore: add dcoumention and endpoint url to method docstrings in charmstore.py
  canonicalwebteam/store_api/stores/charmstore.py
Labels: Review: Code needed
